language: python
matrix:
  include:
    - python: "2.6"
      env: PLONE=4.0
    - python: "2.6"
      env: PLONE=4.1
    - python: "2.6"
      env: PLONE=4.2
    - python: "2.7"
      env: PLONE=4.3
    - python: "2.7"
      env: PLONE=5.0
install: make plone$PLONE
script: ./bin/test
cache:
  directories:
  - $TRAVIS_BUILD_DIR/eggs
